### ISSUE TITLE
React-Native web3auth.login issue when redirecting back to app after login

### ISSUE THREAD

**Issue by azazmushtaq** [Web3Auth/examples#14]
After Successful login in the browser it redirects back to the application with an error

[TypeError: undefined is not a function]

No problem from the browser end but the app end.

Can you please help me out.

Attaching a video of app working

https://drive.google.com/file/d/1fzdx2lDeMkkKsomhxZnSpj08279slnk_/view?usp=drivesdk

**Comment by yashovardhan** [comment]
hey @azazmushtaq can you please try again? There were a few errors in android integration, we fixed that a few weeks ago. It should work as expected now.

**Comment by azazmushtaq** [comment]
yes it worked... one thing more when there will be the Feature of
Import External Solana wallets be integrated in React Native  Sdk?

**Comment by yashovardhan** [comment]
As of now we don't have that on the roadmap. It will be great if you can suggest in the feature requests discussions, so that we can look into it 😄 https://github.com/orgs/Web3Auth/discussions/categories/feature-requests

Closing this issue for now. Please ask any support questions in the GitHub Discussions for prompt responses.
